'Hello, Java';
var mything, numnine, strnine, grt, Name, name_orz, name_orz_week, name_orz_mo, name_orz_tu, name_orz_wen, name_orz_th, name_orz_fr, name_orz_sat, name_orz_su, name_vetr, name_vetr_week, name_vetr_mo, name_vetr_tu, name_vetr_wen, name_vetr_th, name_vetr_fr, name_vetr_sat, name_vetr_su;
mything=5;
mything='строка';
numnine = 9;
strnine = '9';
numnine + numnine;
strnine + strnine;
grt = 'Привет, ';
Name = 'Ник';
grt+Name;
Name.length;
name_orz = 'орз';
name_vetr ='ветрянка';
name_orz_mo = 2;
name_orz_tu = 1;
name_orz_wen= 4;
name_orz_th=3;
name_orz_fr=6;
name_orz_sat=1;
name_orz_su=0;
name_orz_week=name_orz_mo+name_orz_tu+name_orz_wen+name_orz_th+name_orz_fr+name_orz_sat+name_orz_su;
name_vetr_mo=1;
name_vetr_tu=2;
name_vetr_wen=4;
name_vetr_th=1;
name_vetr_fr=3;
name_vetr_sat=5;
name_vetr_su=2;
name_vetr_week=name_vetr_mo+name_vetr_tu+name_vetr_wen+name_vetr_th+name_vetr_fr+name_vetr_sat+name_vetr_su;
name_orz+name_orz_week+name_vetr+name_vetr_week;